import { useMemo, useState } from 'react';
import * as api from '../services/api';
import { useStore } from '../store';
const DOT: Record<string, string> = { pending: 'bg-amber-400', running: 'bg-sky-400 animate-pulse', awaiting_approval: 'bg-amber-400', waiting_for_user: 'bg-violet-400', completed: 'bg-emerald-400', failed: 'bg-red-400', cancelled: 'bg-zinc-400' };
function relative(iso: string): string { const d = Date.now() - new Date(iso).getTime(); return d < 60000 ? '刚刚' : d < 3600000 ? `${Math.floor(d / 60000)} 分钟前` : d < 86400000 ? `${Math.floor(d / 3600000)} 小时前` : new Date(iso).toLocaleDateString('zh-CN'); }
export function SessionSidebar(props: { collapsed: boolean; onToggleCollapse: () => void; activeConversationId: string | null; onSelect: (id: string) => void; onNewSession: () => void }) {
  const { state, loading, loadError, refreshConversation } = useStore();
  const [query, setQuery] = useState(''); const [renaming, setRenaming] = useState<string | null>(null); const [title, setTitle] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const rooms = useMemo(() => state.conversations.filter(room => `${room.title} ${room.latestMessage ?? ''}`.toLowerCase().includes(query.trim().toLowerCase())), [state.conversations, query]);
  async function saveTitle() { if (!renaming || !title.trim() || busy) return; setBusy(true); setError(''); try { await api.renameConversation(renaming, title.trim()); await refreshConversation(); setRenaming(null); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); } }
  if (props.collapsed) return <aside className="flex w-12 shrink-0 flex-col items-center border-r border-zinc-800 bg-zinc-900/70 py-2"><button onClick={props.onToggleCollapse} className="h-11 w-11 rounded-lg text-zinc-300 hover:bg-zinc-800" aria-label="展开聊天室">»</button><button onClick={props.onNewSession} className="h-11 w-11 rounded-lg text-violet-300 hover:bg-zinc-800" aria-label="新聊天室">＋</button></aside>;
  return <aside className="flex h-full w-full shrink-0 flex-col border-r border-zinc-800 bg-zinc-900/70 md:w-64">
    <div className="flex gap-2 border-b border-zinc-800 p-3"><button onClick={props.onNewSession} className="min-h-11 flex-1 rounded-lg bg-violet-500/20 px-3 text-sm text-violet-200">＋ 新聊天室</button><button aria-label="收起聊天室" onClick={props.onToggleCollapse} className="h-11 w-11 rounded-lg hover:bg-zinc-800">«</button></div>
    <div className="p-3"><input aria-label="搜索聊天室" value={query} onChange={e => setQuery(e.target.value)} placeholder="搜索聊天室…" className="input text-sm" /></div>
    <div className="min-h-0 flex-1 overflow-y-auto p-2">{rooms.map(room => <div key={room.id} className={`relative mb-2 rounded-xl ${room.id === props.activeConversationId ? 'bg-violet-500/15 ring-1 ring-violet-500/40' : 'hover:bg-zinc-800/70'}`}>
      {renaming === room.id ? <form className="space-y-2 p-3" onSubmit={e => { e.preventDefault(); void saveTitle(); }}><input autoFocus aria-label="新的房间名称" maxLength={80} value={title} onChange={e => setTitle(e.target.value)} className="input text-sm" onKeyDown={e => { if (e.key === 'Escape') setRenaming(null); }} />{error && <p role="alert" className="text-xs text-red-300">{error}</p>}<div className="flex gap-2"><button disabled={busy || !title.trim()} className="rounded bg-violet-500 px-3 py-2 text-xs disabled:opacity-40">保存</button><button type="button" disabled={busy} className="rounded bg-zinc-800 px-3 py-2 text-xs" onClick={() => setRenaming(null)}>取消</button></div></form> : <><button onClick={() => props.onSelect(room.id)} aria-current={room.id === props.activeConversationId ? 'page' : undefined} className="w-full rounded-xl p-3 pr-12 text-left"><div className="flex items-center gap-2"><span className={`h-2 w-2 shrink-0 rounded-full ${DOT[room.latestRunStatus ?? ''] ?? 'bg-zinc-400'}`} /><span className="min-w-0 flex-1 truncate text-sm">{room.title}</span></div><p className="mt-1 truncate text-xs text-zinc-400">{room.latestMessage ?? `${room.runCount} 轮执行`}</p><p className="mt-2 text-xs text-zinc-400">{room.agentIds.length} 位房间成员 · {relative(room.updatedAt)}</p></button><button aria-label={`重命名${room.title}`} title="重命名" className="absolute right-1 top-1 h-11 w-11 rounded-lg text-zinc-400 hover:bg-zinc-800" onClick={() => { setRenaming(room.id); setTitle(room.title); setError(''); }}>✎</button></>}
    </div>)}{!rooms.length && <p role="status" className="p-6 text-center text-sm text-zinc-400">{loading ? '正在加载聊天室…' : loadError ? '聊天室加载失败' : query ? '没有找到匹配的聊天室' : '还没有聊天室，创建一个开始协作'}</p>}</div>
  </aside>;
}
